### PR TITLE
Services shortcode

### PR DESCRIPTION
**Pull request by aaaaargZombies**
Add a short code for services, it works much the same way as the values shortcode in that it it breaks up the `.Inner` string and adds the needed HTML tags.

### CODE REVIEW

**Comment by SamWhited** [comment]
So I think my hesitation with this has partially been that I don't understand the benefit from this refactor, but also that I don't understand what the CSS class gives us. This adds more code that can go wrong so that we can have the semantic meaning of things in the CSS as well as the HTML. Why name something ".section_title" for example instead of just "section h1" or whatever, which is obviously the section title? It seems to me that this just adds extra coupling that's not necessary and makes things harder to read. I also don't like the double underscore, that seems pointless to me, but that's less of a big deal as it doesn't really matter in any way and is just part of the naming convention. If this is all part of BEM, I suppose I'm pushing back against its use. It has not made the code easier to read or maintain in any way that I can see. That being said, I'm not a CSS expert by any means and am open to being corrected on this.

Getting rid of the various section wrappers does seem nice though.

**Comment by aaaaargZombies** [comment]
I think you've raised a few questions so I'll try to address them as best I can, I also can't really claim to be an expert in any of this but I'll try and explain my thought process at least.

> I don't understand the benefit from this refactor

The main aim is to make the site look like the design that I drew up, everything beyond that is an implementation detail. I'm very open to doing it a different way but I already had a bunch of code that I'd wrote as a mockup and was hoping to move things along quickly.

> Why name something ".section_title" for example instead of just "section h1"

I think this could be fine for the site as is but one of the major issue people run into writing CSS is the lack of scope. If we want to expand the site later it's not unlikely to have a `h1` nested in a `section`. Then we have to worry about conflicting styles. It's then very easy to add bugs in to a part of the site you're not looking at when you're trying to style a new section.

> It has not made the code easier to read or maintain in any way that I can see.

Obviously I can't disagree with how you feel about this, if that's how your experiencing it than I can see it being really annoying. I'm having similar feelings interacting with Hugo and wondering why I can't do things like add numbers together with a `+` operator!

I suspect that BEM will not make the code easier to read and legibility and maintainabilty are closely related. In theory the naming conventions should provide some of that context. `values__title` is the title element that lives in the values block but that requires some familiarity with the convention.

What it should do is reduce the amount of code that needs to be read when interacting with any one part of the site. Bringing the component model of web development to CSS is an ongoing battle and there are multiple ways in which people are doing it.

- [css modules](https://github.com/css-modules/css-modules)
- [styled components](https://github.com/styled-components/styled-components)
- [emotion](https://github.com/emotion-js/emotion)
- [scoped css](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles)
- [svelte](https://svelte.dev/tutorial/styling)
- You could probably do something similar by using a class at the top level of your nested SASS.

Of the options that are practice based rather than tooling based BEM seems to be the one left standing after many years. Stylistically it has many detractors (`__` instead of `_`) and it would also be possible to roll our own but I like the idea of someone new coming to the codebase being more likely to bring a frame of reference.

BEM and CSS modules are the things I'm more familiar with but I think Hugo has a built in SASS processor so that might be an avenue to explore.

I've also realised I didn't answer this question from elsewhere properly.

> I don't see how that precludes keeping a generic section shortcode though?

Partially this was an aesthetic concern, I didn't like the idea of having to pass lots of arguments that weren't content to the shortcodes. Again I also preferred the idea of limiting the scope so that these sections could be redesigned later if we wanted without impacting other sections. I see that could still be done if we used extremely generic shortcodes bound to html elements and passed in classes but I wonder if we'd just be better off using raw HTML at that point.

Anyway sorry this turned into an essay. Thanks for your patience working through this process. As I said at the top, my main concern is moving the codebase in the direction of the design. I would still rather use partials / front matter / BEM but I am happy to try a different approach. I have the time and it's already helped me get a better understanding of Hugo and git so no complaints from me.

**Comment by SamWhited** [comment]
On August 15, 2021 3:39:37 PM UTC, aaaaargZombies ***@***.***> wrote:
>The main aim is to make the site look like the design that I drew up, everything beyond that is an implementation detail.

Sorry, to be clear I meant the change in implementation specifically. I suppose part of my confusion and the reason I'm having difficulty reviewing this is that we're doing a code refactor and visual changes at the same time. It seems like it would be easier to keep these separate, which is why I tried to pull some of the visual stuff out of the pr. Otherwise if we want the visual changes but don't want a code change or visa versa it becomes more work for you.

>I think this could be fine for the site as is but one of the major issue people run into writing CSS is the lack of scope. If we want to expand the site later it's not unlikely to have a `h1` nested in a `section`. Then we have to worry about conflicting styles. It's then very easy to add bugs in to a part of the site you're not looking at when you're trying to style a new section.

It seems like the logical thing to do would be to have "#services h1" or ".columns-section h1" (more or less what we had before) then, not give each style of every element and child its own class. This will just lead to difficulty maintaining things, I suspect.


>I suspect that BEM will not make the code easier to read and legibility and maintainabilty are closely related. In theory the naming conventions should provide some of that context. `values__title` is the title element that lives in the values block but that requires some familiarity with the convention.

I'm not so much concerned with the naming convention as I am with the proliferation of unique classes. The main benefit to cascading style sheets is the "cascading" part and styling everything individually seems like it gets rid of that benefit.

>- [css modules](https://github.com/css-modules/css-modules)
>- [styled components](https://github.com/styled-components/styled-components)
>- [emotion](https://github.com/emotion-js/emotion)
>- [scoped css](https://vue-loader.vuejs.org/guide/scoped-css.html#mixing-local-and-global-styles)
>- [svelte](https://svelte.dev/tutorial/styling)
>- You could probably do something similar by using a class at the top level of your nested SASS.

All of these feel unnecessary to me. It's just a tiny brochure site, anything beyond a tiny bit of css feels like premature optimization and a bigger surface area for bugs and brittleness.

>BEM and CSS modules are the things I'm more familiar with but I think Hugo has a built in SASS processor so that might be an avenue to explore.

Strong opposition to adding more tools and layers of abstraction from me unless we have an urgent operational reason for doing so. This is the only part of this I feel strongly about :)

I still don't understand BEM, never having heard of it before this, but reading over it I suspect it will do the opposite of what it intends and we should work to understand and design reliable systems ourselves instead of following a set of (IMO questionable) rules.

>Partially this was an aesthetic concern, I didn't like the idea of having to pass lots of arguments that weren't content to the shortcodes.

Fair.


All this probably should have been prefixed with the fact that I am likely not going to be the web frontend person in the co-op and therefore my opinion should probably carry very little weight, I don't mean to push back excessively, I just wouldn't feel comfortable doing code review without understanding fully what's going on here and how it will affect us going forward.

—Sam

**Comment by aaaaargZombies** [comment]
OK well the "portMockup" branch pretty much works as a website so if we suddenly find ourselves wanting to link it to a potential client or something we can use that. In the meantime I'll work on trying to implement these visual changes using more element selectors. :+1:

**Comment by loppear** [comment]
I'm coming from a mostly-css-agnostic place here, mostly relied on Bootstrap in recent years with some styled-components-like, and therefore have been able to ignore SASS etc except as a build step. I rarely have had to think about CSS being maintained overall, either peripheral tweaks or component-bound (maintained modularly in parallel with the markup/js implementation that is the primary organizing approach)

I take @aaaaargZombies list of potential approaches to say "every project takes some approach to reuse and modularization of css, I've picked BEM for being lightweight (convention, not tooling, not driven by another stack choice here since this is a brochure site) and as a vocabulary for evaluating how we've organized our styles."

BEM is new to me but also makes sense, coming from more Components work than else, in avoiding pitfalls that ad hoc or bootstrap css end up in around reuse at the html/css boundary, in avoiding relying on nesting or thematic concerns exclusively. And it seems well-aligned to shortcodes as hugo's approach to modularizing markup, I can easily see how block-level shortcodes would be the template components that match to appearance styles. 

----

This PR seems like a good refactor direction, looks cleaner than the prior attempt #9. I feel a related itch to @SamWhited on whether the right "block" here is a more generic `section` vs these `values`, `services` (and generally wouldn't have concerns about shortcodes taking arguments to use as block class prefix, for instance, but less so if it were used for conditionally branching the markup/implementation). As a BEM question, whether Values and Services are the right "logically and functionally independent page components".

But I'm also fine with that being an incremental potential refactor from looking at the overlap between both the shortcode implementations and the css, and probably not motivated at this point.

**Review by SamWhited — APPROVED** [review]
Re-reviewing since it's been a while (continued apologies): I do like the way this shortcode works better, but also worry that it would be more brittle. I am game to merge this or leave it out, though I don't think it's necessary at this time as the current thing isn't broken. I leave it in your capable hands!

I guess I vote -0, I don't know that it's necessary and I'm worried about a few minor things, but I wouldn't block it if someone wants to merge it.

**Pull request closed without merging**
