### PR TITLE
Header experiment - center image and title, exclude description

### PR DESCRIPTION
**Pull request by aaaaargZombies**
This centered layout happened by accident while I was making some changes but I think I might prefer it.

Just putting it out there.

### CODE REVIEW

**Comment by SamWhited** [comment]
I don't love it personally; I end up with lot more negative space on the screen than before. That being said, I don't love slogans either but couldn't think of a better one, so seeing that removed is kind of nice. I defer to others though; I'm not against merging this.

**Comment by loppear** [comment]
I prefer the original, the subtitle is a helpful introduction / statement of purpose I think, and balances the design for me (vs balancing by centering).

**Comment by SamWhited** [comment]
Are we still considering this one? After thinking about it more I agree with @loppear, but I also don't have strong feelings either way and am okay with leaving it up to @aaaaargZombies. Maybe @nthall has opinions?

**Comment by aaaaargZombies** [comment]
I still think I like it more in isolation but I agree that having a one line introduction would be really helpful for people who haven't spent several hours chatting about what we are.

Closing!

**Pull request closed without merging**
