### PR TITLE
all: serve fonts locally

### PR DESCRIPTION
**Pull request by SamWhited**
I have no idea if this is the best, or even an okay, way to do this or not.

### CODE REVIEW

**Comment by aaaaargZombies** [comment]
Had to dig into MDN to check but it all looks good. I don't really understand which parts you've included with `unicode-range` but I guess if anythings missing that will be a good place to check.

There's an additional mono font and a different weight used as bold in the original design. But this looks compatible with the main branch.

**Comment by SamWhited** [comment]
I can go ahead and add those; what weight do you want?

**Comment by aaaaargZombies** [comment]
900 for Alegreya, the other one was "source code pro" also in 900.

**Comment by SamWhited** [comment]
Added all the fonts; we can modify the CSS as we have other fonts to use (to avoid adding more unnecessarily). It might also be worth seeing if we can tweak the design to just use a single bold weight to save some bandwidth and avoid any flash of unstyled text issues as much as possible, but we'll have to play with that when we get there later.

**Comment by aaaaargZombies** [comment]
Great that gives us some flexibility, I'd be happy if this is merged in and we tweak CSS later.

The other version just switches out 700 for 900 so shouldn't add any extra requests.

**Comment by SamWhited** [comment]
oops, good catch on the preconnect, thanks!

**Pull request merged**
